import { Header } from '@/components/Header/Header';
import { roboto } from './fonts';
import './globals.css';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={roboto.className}>
                <Header />
                {children}
            </body>
        </html>
    );
}
