import { Header } from '@/components/Header/Header';
import { roboto } from './fonts';
import './globals.css';
import styles from './layout.module.css';
import { Footer } from '@/components/Footer/Footer';
import { ModalsContainer } from '@/components/ModalsContainer/ModalsContainer';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={roboto.className}>
                <Header />
                <main className={styles.main}>{children}</main>
                <Footer />
                <ModalsContainer />
            </body>
        </html>
    );
}
